#ссылка на github: https://github.com/bigvilka/software_engineering

swagger: "2.0"
info:
  description: "Модуль представляет из себя *API* приложение на *python3.6.0*"
  version: "1.0.0"
  title: "Модуль API проекта Программная инженерия"
servers:
- url: http://localhost:5000
tags:
- name: "Добавление заметки"
  description: "Принимает параметры от клиента для создания заметки"
- name: "Удаление заметки"
  description: "Удаляет заметку по номеру"
- name: "Получение заметки по ее идентификатору"
  description: "Возвращает заметку с определенным номером"
- name: "Редактирование заметки по ее идентификатору"
  description: "Обновляет содержимое заметки по ее номеру"
- name: "Получение заметок по запросу"
  description: "Возвращает заметки, в которых есть указанная подстрока"
paths:
  /notes:
    post:
      tags:
      - "Добавление заметки"
      summary: "Добавляет заметки"
      parameters:
      - in: "body"
        name: "body"
        description: "Пример запроса"
        required: true
        schema:
          $ref: "#/definitions/create"
      responses:
        204:
          description: "Пустое содержимое"
        201:
          description: OK
    get:
      tags:
      - "Получение заметок по запросу"
      summary: "Возвращает все заметки с указанным вхождением"
      parameters:
      - in: query
        name: query
        description: "Пример запроса"
        required: true
        schema:
          $ref: "#/definitions/query"
      responses:
        200:
          description: OK
        400:
          description: "Не найдены заметки с таким запросом"
  /notes/{id}:
    delete:
      tags:
      - "Удаление заметки"
      summary: "Удаляет заметку"
      parameters:
      - in: "path"
        name: "id"
        description: "Номер заметки"
        type: integer
        default: "1"
        required: true
      responses:
        400:
          description: "Не найдена заметка с таким номером"
        200:
          description: OK
    get:
      tags:
      - "Получение заметки по ее идентификатору"
      summary: "Возвращает заметку с определенным номером"
      parameters:
      - in: "path"
        name: "id"
        description: "Номер заметки"
        type: integer
        default: "1"
        required: true
      responses:
        200:
          description: OK
    put:
      tags:
      - "Редактирование заметки по ее идентификатору"
      summary: "Обновляет поля заметки с определенным номером"
      parameters:
      - in: "path"
        name: "id"
        description: "Номер заметки"
        type: integer
        default: "1"
        required: true
      responses:
        400:
          description: "Не найдена заметка с таким номером"
        202:
          description: Содержимое обновлено
        204:
          description: "Пустое содержимое"
definitions:
  create:
    type: "object"
    required:
    - "content"
    properties:
      content:
        type: string
        example: "Выкинуть мусор, решить программную инженерию"
  query:
    type: string
    enum: ["решить"]